require_relative '../../util/enum'

module MangoModel

  # Dispute reason types enumeration
  class DisputeReasonType
    extend Enum

    DUPLICATE = value 'DUPLICATE'

    FRAUD = value 'FRAUD'

    PRODUCT_UNACCEPTABLE = value 'PRODUCT_UNACCEPTABLE'

    UNKNOWN = value 'UNKNOWN'

    OTHER = value 'OTHER'

    REFUND_CONVERSION_RATE = value 'REFUND_CONVERSION_RATE'

    LATE_FAILURE_INSUFFICIENT_FUNDS = value 'LATE_FAILURE_INSUFFICIENT_FUNDS'

    LATE_FAILURE_CONTACT_USER = value 'LATE_FAILURE_CONTACT_USER'

    LATE_FAILURE_BANKACCOUNT_CLOSED = value 'LATE_FAILURE_BANKACCOUNT_CLOSED'

    LATE_FAILURE_BANKACCOUNT_INCOMPATIBLE = value 'LATE_FAILURE_BANKACCOUNT_INCOMPATIBLE'

    LATE_FAILURE_BANKACCOUNT_INCORRECT = value 'LATE_FAILURE_BANKACCOUNT_INCORRECT'

    AUTHORISATION_DISPUTED = value 'AUTHORISATION_DISPUTED'
  end
end