require_relative '../../util/enum'

module MangoModel

  # KYC Document refusal reasons enumeration
  class KycDocRefusedReasonType
    extend Enum

    DOCUMENT_UNREADABLE = value 'DOCUMENT_UNREADABLE'

    DOCUMENT_NOT_ACCEPTED = value 'DOCUMENT_NOT_ACCEPTED'

    DOCUMENT_HAS_EXPIRED = value 'DOCUMENT_HAS_EXPIRED'

    DOCUMENT_INCOMPLETE = value 'DOCUMENT_INCOMPLETE'

    DOCUMENT_MISSING = value 'DOCUMENT_MISSING'

    DOCUMENT_DO_NOT_MATCH_USER_DATA = value 'DOCUMENT_DO_NOT_MATCH_USER_DATA'

    DOCUMENT_DO_NOT_MATCH_ACCOUNT_DATA = value 'DOCUMENT_DO_NOT_MATCH_ACCOUNT_DATA'

    SPECIFIC_CASE = value 'SPECIFIC_CASE'

    DOCUMENT_FALSIFIED = value 'DOCUMENT_FALSIFIED'

    UNDERAGE_PERSON = value 'UNDERAGE_PERSON'

    OTHER = value 'OTHER'

    TRIGGER_PEPS = value 'TRIGGER_PEPS'

    TRIGGER_SANCTIONS_LISTS = value 'TRIGGER_SANCTIONS_LISTS'

    TRIGGER_INTERPOL = value 'TRIGGER_INTERPOL'
  end
end